"""empty message

Revision ID: 18bce7ef8419
Revises: 7c85d322505c
Create Date: 2024-10-12 14:10:03.114021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bce7ef8419'
down_revision = '7c85d322505c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_meets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_1_tickets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tier_2_tickets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tier_3_tickets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_meets', schema=None) as batch_op:
        batch_op.drop_column('tier_3_tickets')
        batch_op.drop_column('tier_2_tickets')
        batch_op.drop_column('tier_1_tickets')

    # ### end Alembic commands ###
