"""empty message

Revision ID: 1e36db301c64
Revises: 18bce7ef8419
Create Date: 2024-10-18 13:57:33.407384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e36db301c64'
down_revision = '18bce7ef8419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_meets', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_meets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
