"""added reserved variable for spots

Revision ID: 27c1c5b6bde4
Revises: 978f767d0e6d
Create Date: 2024-06-18 14:43:53.911488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c1c5b6bde4'
down_revision = '978f767d0e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('reserved')

    # ### end Alembic commands ###
