"""removed meet name

Revision ID: 9353a0dcd017
Revises: ce597c8c9b6c
Create Date: 2024-10-31 11:07:34.293291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9353a0dcd017'
down_revision = 'ce597c8c9b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('meet_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
