"""added name to meets

Revision ID: b77e19c10ae2
Revises: 1ef816b62acf
Create Date: 2024-06-27 12:47:21.020337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77e19c10ae2'
down_revision = '1ef816b62acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_meets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_meets', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
